version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-cdk-core
    versions:
    - 1.100.0
    - 1.87.1
    - 1.88.0
    - 1.89.0
    - 1.90.0
    - 1.90.1
    - 1.91.0
    - 1.92.0
    - 1.93.0
    - 1.94.1
    - 1.95.1
    - 1.96.0
    - 1.97.0
    - 1.98.0
    - 1.99.0
  - dependency-name: policy-sentry
    versions:
    - 0.11.3
    - 0.11.5
    - 0.11.8
    - 0.11.9
