[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aws-iam-db"
version = "0.0.5"
description = "AWS IAM Database"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["requests", "typer", "sqlalchemy", "beautifulsoup4"]

[project.scripts]
aws-iam-db = "aws_iam_db.__main__:main"
